---
booktitle: Proceedings of the International Conference on Neuro-symbolic Systems
shortname: NeuS
year: '2025'
volume: '288'
start: &1 2025-05-28
end: 2025-05-30
published: 2025-07-08
conference_number: '2'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: NeuS
month: 0
cycles: false
bibtex_editor: Pappas, George and Ravikumar, Pradeep and Seshia, Sanjit A.
editor:
- given: George
  family: Pappas
- given: Pradeep
  family: Ravikumar
- given: Sanjit A.
  family: Seshia
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the International Conference on Neuro-symbolic Systems
    Held in University of Pennsylvania, Philadelphia, Pennsylvania, USA on 28-30 May 2025

  Published as Volume 288 by the Proceedings of Machine Learning Research on 08 July 2025.

  Volume Edited by:
    George Pappas
    Pradeep Ravikumar
    Sanjit A. Seshia

  Series Editors:
    Neil D. Lawrence
date_str: 28--30 May
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v288"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v288
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v288
email: ''
conference:
  name: International Conference on Neuro-symbolic Systems
  url: https://neus-2025.github.io/
  location: University of Pennsylvania, Philadelphia, Pennsylvania, USA
  dates:
  - *1
  - 2025-05-29
  - 2025-05-30
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: volume288_clean.bib
# Site settings
# Original source:  volume288_clean.bib
